services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbs
    command: hbbs
    environment:
      - RUST_LOG=debug
    volumes:
      - ./data:/root
    ports:
      - "127.0.0.1:21114:21114"
      - "127.0.0.1:21115:21115"
      - "127.0.0.1:21116:21116"
      - "127.0.0.1:21116:21116/udp"
    restart: unless-stopped
    depends_on:
      - hbbr
    networks:
      - rustdesk

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbr
    command: hbbr
    environment:
      - RUST_LOG=debug
    volumes:
      - ./data:/root
    ports:
      - "127.0.0.1:21117:21117"
    restart: unless-stopped
    networks:
      - rustdesk

networks:
  rustdesk:
    driver: bridge
