-- exec-debug-init-pg.sql
-- Idempotent PG table creation for exec-empty instrumentation (CHG-0861)
-- Run: bash scripts/db-raw.sh -f scripts/exec-debug-init-pg.sql
--
-- Schema:
--   id            UUID PRIMARY KEY (generated by wrapper, not PG)
--   timestamp     TIMESTAMPTZ NOT NULL
--   command       TEXT
--   exit_code     INTEGER
--   stdout        TEXT
--   stderr        TEXT
--   process_count INTEGER
--   ulimit_u      INTEGER
--   calling_agent TEXT
--   session_type  TEXT
--   source        TEXT   -- 'file-only' | 'pg' | 'both'
--   created_at    TIMESTAMPTZ DEFAULT NOW()
--
-- Indexes for query performance:
--   idx_exec_debug_ts     on (timestamp DESC)
--   idx_exec_debug_exit   on (exit_code)  — quick empty/non-zero lookups

CREATE TABLE IF NOT EXISTS state_exec_debug (
    id              UUID PRIMARY KEY,
    timestamp       TIMESTAMPTZ NOT NULL,
    command         TEXT,
    exit_code       INTEGER,
    stdout          TEXT,
    stderr          TEXT,
    process_count   INTEGER,
    ulimit_u        INTEGER,
    calling_agent   TEXT,
    session_type    TEXT,
    source          TEXT DEFAULT 'pg',
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes (IF NOT EXISTS for idempotency)
CREATE INDEX IF NOT EXISTS idx_exec_debug_ts ON state_exec_debug (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_exec_debug_exit ON state_exec_debug (exit_code);
